### ISSUE TITLE
I have to scroll up and down to add points to tier 1

### ISSUE THREAD

**Issue by ghost** [ja837/PD2Skills#16]
Please help me make the best builds

**Comment by jamieadkins95** [comment]
issue with list adapter. gonna have to use notifydatasetchanged()

**Comment by jamieadkins95** [comment]
Might get rid of the list all together. Possibly worth creating purpose built view.

**Comment by jamieadkins95** [comment]
Fixed in v1.1.1. Had to use getItem() and notifydatasetchanged()
